# Generated by Django 4.2.5 on 2023-11-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_number_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='date last update'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date joined'),
        ),
    ]
