# Generated by Django 4.2.5 on 2023-11-10 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_date_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='Receiver',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)], verbose_name='Postal Code'),
        ),
    ]
