# Generated by Django 4.2.5 on 2023-11-10 14:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraddress_receiver_alter_useraddress_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.PositiveIntegerField(validators=[accounts.models.validate_postal_code], verbose_name='Postal Code'),
        ),
    ]
