# Generated by Django 4.2.5 on 2023-11-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraddress_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='Receiver',
            field=models.CharField(max_length=50, verbose_name='Receiver name'),
        ),
    ]
