# Generated by Django 4.2.5 on 2023-11-16 13:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_useraddress_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='Receiver',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_last_update',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='receiver_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
