# Generated by Django 4.2.5 on 2023-11-24 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.CharField(default=1, max_length=50, verbose_name='Receiver name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
