# Generated by Django 4.2.5 on 2023-10-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rate',
            field=models.FloatField(default=0),
        ),
    ]
