# Generated by Django 4.2.5 on 2023-10-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_is_discount_alter_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='average_rate',
        ),
        migrations.AlterField(
            model_name='product',
            name='og_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Original Price'),
        ),
    ]
