# Generated by Django 4.2.5 on 2023-09-25 01:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_is_active_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscategory',
            name='status',
        ),
        migrations.AlterField(
            model_name='product',
            name='og_price',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=30, verbose_name='Original Price'),
        ),
        migrations.AlterField(
            model_name='productscategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
