# Generated by Django 4.2.5 on 2023-11-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_average_rate_alter_product_og_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Text'),
        ),
    ]
