# Generated by Django 4.2.5 on 2023-09-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productscategory_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='productscategory',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='child', to='products.productscategory'),
        ),
    ]
