# Generated by Django 4.2.5 on 2023-09-25 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productscategory_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productscategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='productscategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='products.productscategory'),
        ),
    ]
