# Generated by Django 4.2.5 on 2023-09-26 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productscategory_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='products.product')),
            ],
        ),
    ]
