# Generated by Django 4.2.5 on 2023-09-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productrelated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_discount',
        ),
    ]
