# Generated by Django 4.2.5 on 2023-09-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_shop_alter_product_category_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variants',
            name='title',
        ),
        migrations.AddField(
            model_name='variants',
            name='color_or_size',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
