# Generated by Django 4.2.5 on 2023-09-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='rate',
            field=models.IntegerField(choices=[(1, 'very bad'), (2, 'bad'), (3, 'normal'), (4, 'good'), (5, 'very good')], max_length=10, verbose_name='Rate'),
        ),
    ]
