# Generated by Django 4.2.5 on 2023-10-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productcomment_rate_productlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
